### ISSUE TITLE
Kubernetes supports gRPC probes (released in 1.23)

### ISSUE THREAD

**Issue by SergeyKanzhelev** [grpc-ecosystem/grpc-health-probe#109]
Would be nice to mention the built-in support of gRPC probes in Kubernetes. 

See proposed wording: https://github.com/grpc-ecosystem/grpc-health-probe/pull/99

It also may be worth mentioning some differences when grpc-health-probe may be better suited.  I started list here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe

> Before Kubernetes 1.23, gRPC health probes were often implemented using [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe/), as described in the blog post [Health checking gRPC servers on Kubernetes](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/). The built-in gRPC probes behavior is similar to one implemented by grpc-health-probe. When migrating from grpc-health-probe to built-in probes, remember the following differences:
>
>- Built-in probes run against the pod IP address, unlike grpc-health-probe that often runs against 127.0.0.1. Be sure to configure your gRPC endpoint to listen on the Pod's IP address.
>- Built-in probes do not support any authentication parameters (like -tls).
>- There are no error codes for built-in probes. All errors are considered as probe failures.
>- If ExecProbeTimeout feature gate is set to false, grpc-health-probe does not respect the timeoutSeconds setting (which defaults to 1s), while built-in probe would fail on timeout.

Can be tested on GKE:

```
gcloud config set project $PROJECT
gcloud config set compute/zone asia-east1-c

gcloud container clusters create test-grpc \
    --enable-kubernetes-alpha \
    --no-enable-autorepair \
    --no-enable-autoupgrade \
    --release-channel=rapid \
    --cluster-version=1.23

gcloud container clusters get-credentials test-grpc --zone asia-east1-c --project $PROJECT
```

Try something like this pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: etcd-with-grpc
spec:
  containers:
  - name: etcd
    image: k8s.gcr.io/etcd:3.5.1-0
    command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
    ports:
    - containerPort: 2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10
```
