### ISSUE TITLE
Release as debian/rpm package

### ISSUE THREAD

**Issue by acabarbaye** [grpc-ecosystem/grpc-health-probe#132]
For installation, it would really help if the tools was released as a standard package such as rpm or debian.
Since goreleaser is used, it is just a matter of adding the following section 
```
nfpms:
  - formats:
      - apk
      - deb
      - rpm
    license: Apache-2.0
    maintainer: <>
```
