### ISSUE TITLE
Publishing docker image

### ISSUE THREAD

**Issue by shouichi** [grpc-ecosystem/grpc-health-probe#32]
Hi, do you guys have a plan to publish the docker image on docker hub or gcr? We use `grpc-health-probe` as a sidecar and it would be nice if there is an official repository.

**Comment by ahmetb** [comment]
Ideally you shouldn't be running this as a sidecar, but an exec probe in your app container.

Dockerfile instructions are listed here: https://github.com/grpc-ecosystem/grpc-health-probe#example-grpc-health-checking-on-kubernetes

It's unlikely we'll undertake maintenance and hosting of a docker image, given we offer a binary release on a public URL which you can use to build and host your own images.

**Comment by shouichi** [comment]
@ahmetb Thanks for the response. Could you elaborate on why we shouldn't run it as a sidecar? I thought we can determine the healthiness of the pod as a whole even using a sidecar.

**Comment by ahmetb** [comment]
This is not a long running process, hence no sidecar. Please refer to my blog post on Kubernetes.io/blog on advanced health check patterns.

**Comment by shouichi** [comment]
> This is not a long running process, hence no sidecar

We workaround this by shell script. Is that still a problematic?

```
        - name: grpc-health-probe
          image: grpc-health-probe:latest
          # https://stackoverflow.com/a/35770783/2597718
          command: ["sh"]
          args:
            - "-c"
            - "trap : TERM INT; (while true; do sleep 3600; done) & wait"
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9090"]

```
