### ISSUE TITLE
Adds support for additional metadata

### ISSUE THREAD

**Issue by jcchavezs** [grpc-ecosystem/grpc-health-probe#50]
My use case is that I want to disable tracing for health probes. For example: 

```
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5000", "-metadata=b3:0"]
      initialDelaySeconds: 10
```

There are certainly other ways to achieve the same thing but they involve sampling request which is not enabled in many tracing libraries.

**Q: Could add a flag -disable-tracing=true instead?**

Not really, propagation format dictates the metadata key so we can't have just one. I could work on this if you do agree.

Ping @mohit-a21 @adriancole
