### ISSUE TITLE
Relatively high cpu usage

### ISSUE THREAD

**Issue by Kevintjeb** [grpc-ecosystem/grpc-health-probe#54]
Hi,

We've seen that the grpc-health-probe uses relatively high cpu usage on our low-request pods.
We have the following setting for the probe:
```yaml
livenessProbe:
 exec:
  command:
   - /bin/grpc_health_probe
   - -addr=:8081
  failureThreshold: 3
  periodSeconds: 2
  successThreshold: 1
  timeoutSeconds: 1
```

Our go-based app in this case has the following resource requests:
```yaml
resources:
    limits:
       cpu: "1"
       memory: 128Mi
    requests:
       cpu: 250m
       memory: 32Mi
```

This app also has a HPA setup to scale at 80% cpu usage (200m avg).

We've observed the probes to use 300m cpu on average, which causes the HPA to always keep up too many pods

CPU usage over a 7 day period, the drop is where I changed the periodSeconds to '10'
![image](https://user-images.githubusercontent.com/16103844/99145478-7e78bf80-266f-11eb-826e-073a074d50ef.png)

Zoomed in into the last day with the old probe settings, and the drop with the new settings:
![image](https://user-images.githubusercontent.com/16103844/99145490-9e0fe800-266f-11eb-876f-4d249213c21f.png)

The load on our system was the same during these days, so we were essentially wasting cpu.

One last example, where the service is generally only using CPU from the probes:
![image](https://user-images.githubusercontent.com/16103844/99145549-268e8880-2670-11eb-97e6-33ff980a0f81.png)

The 02s interval was taking 300m cpu
The 05s interval was taking 170m cpu
The 10s interval was taking 90m cpu

I've googled and looked through the existing issues but I've not found a clue to this issue. Is this known? I did find some issues with kubernetes exec type of probes, but we prefer to not switch to HTTP probes since these are all GRPC systems.
