### ISSUE TITLE
Example: gRPC health checking on Kubernetes does not work on GKE with mTLS

### ISSUE THREAD

**Issue by PassKit** [grpc-ecosystem/grpc-health-probe#7]
Using mutual TLS, the example provided does not work on GKS when deploying an ingress over a service.  GKE still insists on providing a HTTP2 health check looking for a response from `/`.  This fails since Googles health check has no certificates and so cannot complete a mTLS connection.

My exec readiness and liveliness probes are ignored when the ingress is set up.

```
readinessProbe:
  exec:
    command: ["/hc", "-addr=127.0.0.1:9999", "-tls", "-tls-ca-cert=/tls/ca-chain.pem", "-tls-client-cert=/tls/client.pem", "-tls-client-key=/tls/client-key.pem"]
  initialDelaySeconds: 5
livenessProbe:
  exec:
    command: ["/hc", "-addr=127.0.0.1:9999", "-tls", "-tls-ca-cert=/tls/ca-chain.pem", "-tls-client-cert=/tls/client.pem", "-tls-client-key=/tls/client-key.pem"]
  initialDelaySeconds: 10 
```
