### ISSUE TITLE
Kubernetes not terminating container when health check fails

### ISSUE THREAD

**Issue by samstride** [grpc-ecosystem/grpc-health-probe#83]
Hi,

Thanks for maintaining this utility. I came across it when I was going through the GCP microservices demo project on Github. I have been using it since v0.3.x and has been working well until now.

I'm on Rancher kubernetes `v1.20.9`, Go `v1.17`, grpc_health_probe version `v0.4.5` and using the following dependencies:

```go
google.golang.org/genproto v0.0.0-20210831024726-fe130286e0e2
google.golang.org/grpc v1.40.0
google.golang.org/protobuf v1.27.1
```

I have a GRPC service that does a health check like this:

```go
import (
  .
  .
  healthpb "google.golang.org/grpc/health/grpc_health_v1"
  .
  .
)
.
.
.
grpcServer := grpc.NewServer()

// Register heatlh check server.
healthcheck := health.NewServer()
healthpb.RegisterHealthServer(grpcServer, healthcheck)

go func() {
for {
	serverStatus := healthpb.HealthCheckResponse_SERVING
	healthy := instance.HealthChecks() // calls a method to do some health checks
	if !healthy {
		serverStatus = healthpb.HealthCheckResponse_NOT_SERVING
	}
	instance.logger.Info(serverStatus)
	healthcheck.SetServingStatus("service.namespace", serverStatus)
	time.Sleep(10 * time.Second)
}
}()
```

When I run the program locally, and when the health check fails, I can see the status is being set to `NOT_SERVING`.

When the container runs on kubernetes, and when the health check fails, I can see the status is being set to `NOT_SERVING`. However, the container isn't restarted (terminate + start) automatically on k8s.

My Dockerfile has:

```dockerfile
# Download tool to perform GRPC health checks for k8s.
RUN GRPC_HEALTH_PROBE_VERSION=v0.4.5 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe
```

And my k8s manifest has:

```yaml
readinessProbe:
  exec:
    command:
      [
        "/bin/grpc_health_probe",
        "-addr=:3000",
        "-rpc-timeout=5s",
      ]
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
livenessProbe:
  exec:
    command:
      [
        "/bin/grpc_health_probe",
        "-addr=:3000",
        "-rpc-timeout=5s",
      ]
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
```

I downgraded go to `v.1.16.7` and had the same issue.

What am I missing?

Thanks.
